const fr30DayPlan = [
  {
    day: 1,
    focus: "Framework & Presentation (Part 1)",
    topic: "Conceptual Framework & IAS 1 Presentation",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Basic Statements",
    areas: ["Qualitative characteristics", "Elements of FS", "Objective of general purpose FS"],
    material: "Kaplan Study Text / Notes",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 2,
    focus: "Framework & Presentation (Part 2)",
    topic: "Conceptual Framework & IAS 1 Presentation",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Basic Statements",
    areas: ["Structure of SFP & SOPL", "Current vs Non-current", "Notes to accounts"],
    material: "Kaplan Study Text / Notes",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 3,
    focus: "Revenue (Part 1)",
    topic: "IFRS 15 Revenue from Contracts",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Scenario-based Allocations",
    areas: ["5-Step Model", "Identify contract", "Performance obligations"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 4,
    focus: "Revenue (Part 2)",
    topic: "IFRS 15 Revenue from Contracts",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Scenario-based Allocations",
    areas: ["Transaction price allocation", "Timing of recognition", "Principal vs Agent"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 5,
    focus: "Tangible Assets & Costs",
    topic: "IAS 16 PPE & IAS 23 Borrowing Costs",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Capitalisation tables",
    areas: ["Initial cost", "Depreciation", "Specific vs General borrowings"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 6,
    focus: "Revaluation & Property",
    topic: "IAS 16 PPE & IAS 40 Investment Property",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Revaluation workings",
    areas: ["Revaluation surplus", "Cost vs Fair Value model", "Transfers"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 7,
    focus: "Impairment of Assets",
    topic: "IAS 36 Impairment",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "CGU allocations",
    areas: ["Indicators of impairment", "Value in use", "Cash Generating Units"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 8,
    focus: "Intangible Assets",
    topic: "IAS 38 Intangible Assets",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "R&D Costing",
    areas: ["Research vs Development (PIRATE)", "Useful life", "Amortisation"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 9,
    focus: "Inventory & Grants",
    topic: "IAS 2 Inventory & IAS 20 Government Grants",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "NRV & Grant Amortisation",
    areas: ["Lower of Cost and NRV", "Capital vs Income grants", "Repayment of grants"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 10,
    focus: "Provisions & Post-Year Events",
    topic: "IAS 37 Provisions & IAS 10 Events",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Scenario Analysis",
    areas: ["Recognition criteria", "Onerous contracts", "Adjusting vs Non-adjusting"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 11,
    focus: "Financial Assets & ECL",
    topic: "IFRS 9 Financial Instruments (Part 1)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Amortised Cost Tables",
    areas: ["Amortised cost", "FVTPL vs FVTOCI", "Expected Credit Loss"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 12,
    focus: "Financial Liabilities & Compound",
    topic: "IFRS 9 Financial Instruments (Part 2)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Split Accounting",
    areas: ["Financial liabilities", "Compound instruments (Convertible bonds)"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 13,
    focus: "Income Taxes",
    topic: "IAS 12 Income Taxes",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Deferred Tax Balances",
    areas: ["Current tax", "Temporary differences", "Deferred tax assets/liabilities"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 14,
    focus: "Foreign Currency",
    topic: "IAS 21 Foreign Currency",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Translation Gains/Losses",
    areas: ["Spot rates", "Monetary vs Non-monetary items", "Year-end translation"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 15,
    focus: "EPS & Mid-Point Review",
    topic: "IAS 33 EPS & Weak Areas",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Diluted EPS",
    areas: ["Basic EPS", "Bonus & Rights issues", "Mid-point revision"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 16,
    focus: "Cash Flow Statements",
    topic: "IAS 7 Cash Flow Statements",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Full Cash Flow Statement",
    areas: ["Operating (Indirect)", "Investing", "Financing activities"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 17,
    focus: "Single Entity Prep (Part 1)",
    topic: "Single Entity Financial Statements",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Full SOPL & SFP",
    areas: ["SOPL format", "SFP format", "Year-end adjustments"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 18,
    focus: "Single Entity Prep (Part 2)",
    topic: "Single Entity Financial Statements",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Corrections & Notes",
    areas: ["Prior period errors", "Statement of Changes in Equity", "Disclosure notes"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 19,
    focus: "Group Basics & Goodwill",
    topic: "Consolidation (IFRS 3)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Goodwill Calculation",
    areas: ["Control", "Fair value of consideration", "NCI measurement"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 20,
    focus: "Consolidated SFP",
    topic: "Consolidation (IFRS 10) Part 1",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Full CSFP",
    areas: ["Standard workings (W1-W5)", "Intra-group balances", "PUP"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 21,
    focus: "Consolidated SPLOCI",
    topic: "Consolidation (IFRS 10) Part 2",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Full CSPLOCI",
    areas: ["Line-by-line addition", "Intra-group trading", "Dividends"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 22,
    focus: "Associates",
    topic: "Consolidation (IAS 28)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Equity Accounting",
    areas: ["Significant influence", "Equity method", "PUP on associates"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 23,
    focus: "Complex Consolidation",
    topic: "Consolidation (Practice)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Past Exam Questions",
    areas: ["Mid-year acquisitions", "Fair value adjustments", "Time management"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 24,
    focus: "Profitability & Liquidity",
    topic: "Interpretation & Ratio Analysis (Part 1)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Ratio Calculations",
    areas: ["ROCE, Margins", "Current/Quick ratios", "Asset turnover"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 25,
    focus: "Gearing & Investor Ratios",
    topic: "Interpretation & Ratio Analysis (Part 2)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Risk & Investor Ratios",
    areas: ["Gearing", "Interest cover", "P/E ratio, Dividend yield"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 26,
    focus: "Limitations & Groups",
    topic: "Interpretation & Ratio Analysis (Part 3)",
    hours: "6 - 7 hrs",
    practice: "Section A/B MCQs",
    numericals: "Written Analysis",
    areas: ["Limitations of ratios", "Group structure changes", "Related parties"],
    material: "Kaplan / BPP",
    tasks: ["45m Revise notes", "2-3h Learn topic", "2h MCQs", "1h Practical qs", "30m Formula & Error log"]
  },
  {
    day: 27,
    focus: "Full Mock 1",
    topic: "Mock Exam (ACCA CBE Platform)",
    hours: "3 hrs",
    practice: "Full Exam",
    numericals: "Section C",
    areas: ["Complete syllabus testing under time limits"],
    material: "ACCA Practice Platform",
    tasks: ["Clear desk", "Set 3-hour timer", "Complete Mock 1 in full"]
  },
  {
    day: 28,
    focus: "Review Mock + Weak Topics",
    topic: "Mock Analysis",
    hours: "6 - 7 hrs",
    practice: "Targeted MCQs",
    numericals: "Correcting Section C",
    areas: ["Analyze mistakes", "Revise weak standards", "Update error notebook"],
    material: "Mock Exam Answers",
    tasks: ["45m Read examiner report", "2h Re-do wrong MCQs", "2h Analyze Section C", "1h Revise weak topics"]
  },
  {
    day: 29,
    focus: "Full Mock 2",
    topic: "Mock Exam (Kaplan / BPP)",
    hours: "3 hrs",
    practice: "Full Exam",
    numericals: "Section C",
    areas: ["Final syllabus testing", "Time management"],
    material: "BPP / Kaplan Kit",
    tasks: ["Clear desk", "Set 3-hour timer", "Complete Mock 2 in full"]
  },
  {
    day: 30,
    focus: "Formulas, Review & Mistake Notebook",
    topic: "Pre-Exam Wrap Up",
    hours: "4 - 5 hrs",
    practice: "Light Revision",
    numericals: "Review Formats",
    areas: ["Formula Sheet", "IFRS Review", "Mistake Notebook"],
    material: "Personal Notes & Formula Chart",
    tasks: ["1h Read mistake notebook", "1h Review IFRS rules", "1h Memorize formulas", "Rest well"]
  }
];

window.fr30DayPlan = fr30DayPlan;
